### ISSUE TITLE
Error generate proto files

### ISSUE THREAD

**Issue by KosToZyB** [micro/examples#10]
Hello, Asim!
When I generate code from proto files, I took errors:
> ~/go/src/github.com/micro/examples/booking$ make proto
> for d in api srv; do \
>         for f in $d/**/proto/*.proto; do \
>                 protoc --go_out=plugins=micro:. $f; \
>                 echo compiled: $f; \
>         done \
> done
**> github.com/micro/examples/booking/srv/profile/proto/profile.proto: File not found.
> github.com/micro/examples/booking/srv/rate/proto/rate.proto: File not found.
> api/hotel/proto/hotel.proto: Import "github.com/micro/examples/booking/srv/profile/proto/profile.proto" was not found or had errors.
> api/hotel/proto/hotel.proto: Import "github.com/micro/examples/booking/srv/rate/proto/rate.proto" was not found or had errors.**
> api/hotel/proto/hotel.proto:18:18: "profile.Hotel" is not defined.
> api/hotel/proto/hotel.proto:19:18: "rate.RatePlan" is not defined.
> compiled: api/hotel/proto/hotel.proto
> compiled: srv/auth/proto/auth.proto
> compiled: srv/geo/proto/geo.proto
> compiled: srv/profile/proto/profile.proto
> compiled: srv/rate/proto/rate.proto

Version protoc:
> $ protoc --version
> libprotoc 3.0.0

Linux:

> $ lsb_release -a
> No LSB modules are available.
> Distributor ID: Ubuntu
> Description:    Ubuntu 17.10
> Release:        17.10
> Codename:       artful

**Comment by KosToZyB** [comment]
This [pull request](https://github.com/micro/examples/pull/11) resolve a problem, but I do not know whether it is possible to use environment variables. 
sorry for my poor english

**Comment by asim** [comment]
Thanks for the fix, it has been merged
