### ISSUE TITLE
Question on "micro/examples/service"

### ISSUE THREAD

**Issue by Shawn-Fan** [micro/examples#103]
Following the instruction of the example, the error message show up,

1. After running "go run main.go" 
     Ias-MacBook:service ia$ go run main.go
2019-12-04 15:57:50.372201 I | Transport [http] Listening on [::]:49908
2019-12-04 15:57:50.372353 I | Broker [http] Connected to [::]:49909
2019-12-04 15:57:50.372855 I | Registry [mdns] Registering node: greeter-b6364fa4-44e3-4d9d-9c5d-69de020a4184

2. After running "go run main.go --run_client"
Ias-MacBook:service ia$ go run main.go --run_client
{"id":"go.micro.client","code":500,"detail":"service greeter: not found","status":"Internal Server Error"}

Could you let me know the reason? Thanks

**Comment by AndreiD** [comment]
please upload your code to a repo and share the link

**Comment by Shawn-Fan** [comment]
Source code: https://github.com/micro/examples/tree/master/service

**Comment by AndreiD** [comment]
no dude. I mean YOUR CODE. what YOU did. Jesuzz.....

**Comment by asim** [comment]
Some macbooks have a firewall enabled which prevents multicast DNS. You will need to disable it.

**Comment by Shawn-Fan** [comment]
@asim Thanks, it works
