### ISSUE TITLE
client can't find the service but server register successfully in linux machine

### ISSUE THREAD

**Issue by binuedwin** [micro/examples#104]
when running the client.go getting this error. 
{"id":"go.micro.client","code":500,"detail":"service go.micro.srv.client: not found","status":"Internal Server Error"}

The server is running and i am able to run micro web and get the list of services
go run main.go --registry=etcd
{"time":"2019-12-12T05:47:47.660104732Z","level":"INFO","prefix":"-","file":"mgodb.go","line":"42","message":"Driver offical - connected to MongoDB!"}
{"time":"2019-12-12T05:47:47.660149984Z","level":"INFO","prefix":"-","file":"mgodb.go","line":"44","message":"Using DB:inventory-services"}
ERROR: <nil>
2019-12-12 05:47:47.660771 I | PIN stock pool calculation service has started and runs once in 5 minutes
2019-12-12 05:47:47.660928 I | PIN stock pool calculation is running...
2019-12-12 05:47:47.661266 I | Transport [http] Listening on 127.0.0.1:8080

**Comment by asim** [comment]
Your client must also specify etcd
