### ISSUE TITLE
The name generated by protoc-gen-micro and protoc-gen-grpc-gateway generate is different 

### ISSUE THREAD

**Issue by codlin** [micro/examples#106]
Hi,
the name generated by protoc-gen-micro and protoc-gen-grpc-gateway generate is different.

the gateway file, see line 31, the type of Client is  `SayClient`
https://github.com/micro/examples/blob/210612de508ab0ce0aada9fa960a84ce279716c4/grpc/gateway/proto/hello/hello.pb.gw.go#L31

the micro file, see line 44, the type of Client is `SayService `
https://github.com/micro/examples/blob/210612de508ab0ce0aada9fa960a84ce279716c4/grpc/greeter/srv/proto/hello/hello.micro.go#L44

this cause gateway raised an exception which is 'can not found SayClient'.

Thanks

**Comment by asim** [comment]
Grpc gateway works with grpc not micro
