### ISSUE TITLE
“micro api --handler=http --address=0.0.0.0:8088” Unable to call api service.

### ISSUE THREAD

**Issue by jococi** [micro/examples#107]
### start
`2020-01-02 14:57:40.410147 I | [api] Registering API HTTP Handler at /{service:[a-zA-Z0-9]+}
2020-01-02 14:57:40.410270 I | [api] HTTP API Listening on [::]:8088
2020-01-02 14:57:40.410353 I | [api] Transport [http] Listening on [::]:44773
2020-01-02 14:57:40.410386 I | [api] Broker [http] Connected to [::]:37715
2020-01-02 14:57:40.410515 I | [api] Registry [mdns] Registering node: go.micro.api-1f71f776-e6c5-4505-8eac-64f578636ff6
`
### api  code:
`package main

import (
	"github.com/gin-gonic/gin"

	"github.com/micro/go-micro/web"
	"log"
)

type Say struct{}

func (s *Say) Anything(c *gin.Context) {
	log.Print("Received Say.Anything API request")
	c.JSON(200, map[string]string{
		"message": "Hi, this is the Greeter API",
	})
}

func main() {

	// Create service
	service := web.NewService(
		web.Name("go.micro.api.greeter"),
	)

	service.Init()

	// Create RESTful handler (using Gin)
	say := new(Say)
	router := gin.Default()
	router.GET("/greeter", say.Anything)
	
	// Register Handler
	service.Handle("/", router)

	// Run server
	if err := service.Run(); err != nil {
		log.Fatal(err)
	}
}`

### CALL: 
http://127.0.0.1:8088/greeter

### return：
`2020-01-02 14:46:38.471894 I | http: proxy error: EOF
127.0.0.1 - - [02/Jan/2020:14:44:36 +0800] "GET /greeter HTTP/1.1" 502 0 "" "Apache-HttpClient/4.5.10 (Java/11.0.5)"
`

**Comment by printfcoder** [comment]
looks like you are using a proxy server, right?

**Comment by jococi** [comment]
> looks like you are using a proxy server, right?

right. Is this mode not supported now?

**Comment by printfcoder** [comment]
Emm. no. it's not micro's problem. you should add the address onto the whitelist.
