### ISSUE TITLE
examples/proxy failed with: "service name is blank"

### ISSUE THREAD

**Issue by doutuiya** [micro/examples#108]
**os**: windows 10
**go-micro**: 1.18.0
**go**: 1.13

**steps:**

> 1. micro.exe proxy
> 2. go run rpc_server.go proxy.go
> 3. go run rpc_client.go  proxy.go

**output:** 
> {"id":"","result":null,"error":"{\"id\":\"go.micro.proxy\",\"code\":400,\"detail\":\"service name is blank\",\"status\":\"Bad Request\"}"}

**Comment by refs** [comment]
We were trying to register a ruby service through the proxy following the instruction on micro/examples at no avail, it keeps complaining the "service name is blank"

We managed to narrow down the issue to `mucp.go` but didn't go further debugging. However found a workaround by changing the registry default namespace to `go.micro.api.registry` and the following request will work:

```curl
curl "http://localhost:8080/registry/register" \
-H "Content-Type: application/json" \
 -d '{"name":"go.micro.api.test", "nodes": [{"id":"whatever", "address": "localhost:9191"}]}' -v
```

Having a look at the proxy code currently

**Comment by k1ng440** [comment]
I can confirm this issue.

**Comment by asim** [comment]
The http proxy was deprecated
