### ISSUE TITLE
service.Service does not implement micro.Service 

### ISSUE THREAD

**Issue by seidu626** [micro/examples#109]
Error: 
go/pkg/mod/github.com/micro/go-plugins/service/kubernetes/v2@v2.0.2/kubernetes.go:30:24: cannot use grpc.NewService(options...) (type service.Service) as type micro.Service in return argument:
	service.Service does not implement micro.Service (wrong type for Init method)
		have Init(...service.Option)
		want Init(...micro.Option)

Code:
package main

import (
	"log"

	"github.com/micro/go-micro/v2"
	_ "github.com/micro/go-plugins/registry/mdns/v2"
	k8s "github.com/micro/go-plugins/service/kubernetes/v2"
	pb "github.com/seidu626/abk-user-service/proto/auth"
)

func main() {

	// Creates a database connection and handles
	// closing it again before exit.
	db, err := CreateConnection()
	defer db.Close()

	if err != nil {
		log.Fatalf("Could not connect to DB: %v", err)
	}

	// Automatically migrates the user struct
	// into database columns/types etc. This will
	// check for changes and migrate them each time
	// this service is restarted.
	db.AutoMigrate(&pb.User{})

	repo := &UserRepository{db}

	tokenService := &TokenService{repo}

	// Create a new service. Optionally include some options here.
	srv := k8s.NewService(

		// This name must match the package name given in your protobuf definition
		micro.Name("abk.auth"),
	)

	// Init will parse the command line flags.
	// srv.Init()

	// Will comment this out now to save having to run this locally
	// publisher := micro.NewPublisher("user.created", srv.Client())

	// Register handler
	pb.RegisterAuthHandler(srv.Server(), &service{repo, tokenService})

	// Run the server
	if err := srv.Run(); err != nil {
		log.Fatal(err)
	}
}

**Comment by vtolstov** [comment]
this is known issue

**Comment by vtolstov** [comment]
needs to fix go-plugins
