### ISSUE TITLE
Request Java Example GRPC

### ISSUE THREAD

**Issue by alienatorZ** [micro/examples#110]
I am having a hard time calling between go-micro and java microservices. I have to resort to just using google/grpc since that works. Could we please get an example of how to call a Java GRPC service?

Thank you!

**Comment by vtolstov** [comment]
Do you want to call java service FROM micro, or you want call micro FROM java?

**Comment by alienatorZ** [comment]
I currently would like to call Java FROM micro. I have a mostly micro setup but I depend on a java service. Whenever I call java from micro I get a transport error text/plain not recognized or similar.

**Comment by k1ng440** [comment]
@alienatorZ this is nothing to do with micro then. 

use the client for whatever the protocol java service is using.
