### ISSUE TITLE
Import should be updated

### ISSUE THREAD

**Issue by mcabezas** [micro/examples#111]
https://github.com/micro/examples/blob/2ee3eac2243266f41550e3c74793ccb5e7c993ec/kubernetes/cmd/health/main.go#L13

Should be replaced to 	`proto "github.com/micro/go-micro/debug/service/proto"`

**Comment by asim** [comment]
Can you PR please?

**Comment by mcabezas** [comment]
Sure, may be I can include the go.mod file to ensure the version for the imports.
