### ISSUE TITLE
Redeclaration in protoc-gen-micro

### ISSUE THREAD

**Issue by nicocesar** [micro/examples#117]
I have:
protoc-gen-go
protoc-gen-micro

And I think that after compiling this happens (this is just one out of many:
```
proto/auth.pb.micro.go:36:6: AuthService redeclared in this block
	previous declaration at proto/auth.micro.go:45:6

```
I can see 

https://github.com/micro/examples/blob/9017cf5cd6c005c4d40f5d8e601ebcb53aceb5a9/booking/srv/auth/proto/auth.micro.go#L45

and 

https://github.com/micro/examples/blob/9017cf5cd6c005c4d40f5d8e601ebcb53aceb5a9/booking/srv/auth/proto/auth.pb.go#L109

Is this expected?

**Comment by vtolstov** [comment]
remove stale generated files, never protoc-gen-micro uses *.pb.micro.go suffix as all other generated proto stuff.

**Comment by nicocesar** [comment]
I fixed my stuff, you can see them in https://github.com/nicocesar/booking

I was reporting this so micro examples can compile.
