### ISSUE TITLE
python proxy example: ConnectionResetError

### ISSUE THREAD

**Issue by damianskobel** [micro/examples#123]
hello guys, 

I'm trying to use proxy sample but I'm getting **ConnectionResetError**

I'm using:
latest micro version
python Python 3.8.2
json-rpc==1.13.0
Werkzeug==1.0.1
requests==2.23.0

I run cmd: micro proxy

console output:
> 2020-04-24 11:30:20  level=info service=proxy Proxy [mucp] serving protocol: grpc
2020-04-24 11:30:20  level=info service=proxy Server [grpc] Listening on [::]:8081
2020-04-24 11:30:20  level=debug service=proxy Registry [memory] Registering node: go.micro.server-1f202749-eb37-4a36-adb1-59902f72c5cb
2020-04-24 11:30:20  level=debug service=proxy Registry added new service: go.micro.server, version: latest
2020-04-24 11:30:20  level=info service=proxy Starting [service] go.micro.proxy
2020-04-24 11:30:20  level=info service=proxy Server [grpc] Listening on [::]:58025
2020-04-24 11:30:20  level=debug service=proxy Registry [mdns] Registering node: go.micro.proxy-1f202749-eb37-4a36-adb1-59902f72c5cb
2020-04-24 11:30:20  level=debug service=proxy [mdns] registry create new service with ip: 192.168.99.1 for: 192.168.99.1
2020-04-24 11:30:21  level=debug service=proxy Router emitting create for route: 192.168.99.1:58025

next I run
proxy/python/rpc_server.py

output:

> Traceback (most recent call last):
>   File "/root/micro-examples/proxy/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 677, in urlopen
>     chunked=chunked,
>   File "/root/micro-examples/proxy/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 426, in _make_request
>     six.raise_from(e, None)
>   File "<string>", line 3, in raise_from
>   File "/root/micro-examples/proxy/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 421, in _make_request
>     httplib_response = conn.getresponse()
>   File "/usr/lib/python3.6/http/client.py", line 1346, in getresponse
>     response.begin()
>   File "/usr/lib/python3.6/http/client.py", line 307, in begin
>     version, status, reason = self._read_status()
>   File "/usr/lib/python3.6/http/client.py", line 268, in _read_status
>     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
>   File "/usr/lib/python3.6/socket.py", line 586, in readinto
>     return self._sock.recv_into(b)
> ConnectionResetError: [Errno 104] Connection reset by peer
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/root/micro-examples/proxy/venv/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
>     timeout=timeout
>   File "/root/micro-examples/proxy/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 725, in urlopen
>     method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
>   File "/root/micro-examples/proxy/venv/lib/python3.6/site-packages/urllib3/util/retry.py", line 403, in increment
>     raise six.reraise(type(error), error, _stacktrace)
>   File "/root/micro-examples/proxy/venv/lib/python3.6/site-packages/urllib3/packages/six.py", line 734, in reraise
>     raise value.with_traceback(tb)
>   File "/root/micro-examples/proxy/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 677, in urlopen
>     chunked=chunked,
>   File "/root/micro-examples/proxy/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 426, in _make_request
>     six.raise_from(e, None)
>   File "<string>", line 3, in raise_from
>   File "/root/micro-examples/proxy/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 421, in _make_request
>     httplib_response = conn.getresponse()
>   File "/usr/lib/python3.6/http/client.py", line 1346, in getresponse
>     response.begin()
>   File "/usr/lib/python3.6/http/client.py", line 307, in begin
>     version, status, reason = self._read_status()
>   File "/usr/lib/python3.6/http/client.py", line 268, in _read_status
>     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
>   File "/usr/lib/python3.6/socket.py", line 586, in readinto
>     return self._sock.recv_into(b)
> urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

is it something or my end or python examples are outdated?

**Comment by asim** [comment]
Outdated examples and deprecated now
