### ISSUE TITLE
Latest example greeter: micro api --handler=api

### ISSUE THREAD

**Issue by DuckulaGL** [micro/examples#130]
os: OSX 10.15
first run:
go run api/api.go
it is OK

second run:
greeter git:(master) ✗ go run srv/main.go
it is OK

third run:
➜ ~ micro api --handler=api
report error:
{"id":"go.micro.client","code":500,"detail":"connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:8081: connect: connection refused"","status":"Internal Server Error"}

So if run "curl "http://localhost:8080/greeter/say/hello?name=John", it reports error too.

If just run "micro api", it runs OK

run "consul agent -dev", greeter api curl invoke still reports error.

English version micro Doc has issues, so who can supply the right description about it. The Chinese doc just has some right description but incomplete.

**Comment by maaars** [comment]
meet same errors

**Comment by asim** [comment]
Works for us at the moment on master. Closing.
