### ISSUE TITLE
auth/main.go

### ISSUE THREAD

**Issue by dean-su** [micro/examples#16]
Unresolved reference 'RegisterAuthHandler' less... (Ctrl+F1) 
Reports unresolved references.

**Comment by asim** [comment]
You have not provided a reference to where this auth/main.go is so I'm assuming booking/srv/auth. As you can see the reference does exist here https://github.com/micro/examples/blob/master/booking/srv/auth/proto/auth.pb.go#L125 and this code compiles fine. If you're recompiling then you need to ensure you are using our fork of protoc-gen-go. https://github.com/micro/protobuf 

```
go get github.com/micro/protobuf/{proto,protoc-gen-go}
```
