### ISSUE TITLE
Recompiled the booking example issues

### ISSUE THREAD

**Issue by dean-su** [micro/examples#17]
$ make proto
for d in api srv; do \
        for f in $d/**/proto/*.proto; do \
                protoc -I. -I/d/GOPATH/src --go_out=plugins=micro:. $f; \
                echo compiled: $f; \
        done \
done
compiled: api/hotel/proto/hotel.proto
compiled: srv/auth/proto/auth.proto
compiled: srv/geo/proto/geo.proto
compiled: srv/profile/proto/profile.proto
compiled: srv/rate/proto/rate.proto
make: write error

## Hi, when I recompiled the *.proto,  the func RegisterAuthHandler that disappeared, and please check the attachment. Thanks!
[diff.after.compiled.txt](https://github.com/micro/examples/files/1734875/diff.after.compiled.txt)

**Comment by asim** [comment]
As mentioned in the previous issue opened. Please install our fork of protoc-gen-go

```
go get github.com/micro/protobuf/{proto,protoc-gen-go}
```

The version built should be in your bin path. If this version is not used, the micro plugin is not found.
