### ISSUE TITLE
Recompiled the booking example issues

### ISSUE THREAD

**Issue by dean-su** [micro/examples#18]
DeanSu@DeanSu-PC MINGW64 /d/GOPATH/bin
$ ll pro*
-rwxr-xr-x 1 DeanSu 197121 4035584 2/18 11:59 protoc.exe*
-rwxr-xr-x 1 DeanSu 197121 4206592 2/18 11:57 protoc-gen-go.exe*

**Comment by asim** [comment]
Please join the slack to debug your development environment issues. This is not a but with the project or the proto. Your dev environment is not using the right protoc-gen-go hence not generating the correct functions.
