### ISSUE TITLE
examples/booking/bin/build.sh wrong

### ISSUE THREAD

**Issue by fasilenko** [micro/examples#2]
Hello, Asim!

Please change in examples/booking/bin/build.sh first line
    **#!/bin/sh**
to
    **#!/bin/bash**
or to
    **#!/usr/bin/env bash**

Old shell (sh) doesn't have pushd internal command.
BTW, inspired because i'm working using zsh, so the same situation :)

Probably it would be better to change directories using another approach described here http://unix.stackexchange.com/questions/272965/pushd-popd-vs-cd-cd-in-bash-and-zsh

1. cd somewhere
2. cd -

Alexander

**Comment by asim** [comment]
Done
