### ISSUE TITLE
Error when run examples/form

### ISSUE THREAD

**Issue by TechMaster** [micro/examples#20]
**1st issue**
1. I follow instructions as ReadMe.md
2. I submit form http://localhost:8082/form the browser navigates to http://localhost:8080/form/submit and says "This site can’t be reached"

**2nd issue**
The file [web/main.go](https://github.com/micro/examples/blob/master/form/web/main.go)
we should change to test uploading binary file
```html
<form action="http://localhost:8080/form/multipart" method="POST" enctype="multipart/form-data">
<input type="text" id="thing" name="thing" />
<button>submit</button>
```
to
```html
<form action="http://localhost:8080/form/multipart" method="POST" enctype="multipart/form-data">
<input type="file" id="thing" name="thing" />
<button>submit</button>
```

**Comment by asim** [comment]
Please PR the fix

**Comment by asim** [comment]
No response. Closing.
