### ISSUE TITLE
Why micro web is so simple and there is no monitoring information

### ISSUE THREAD

**Issue by shihp** [micro/examples#24]
Why micro web is so simple and there is no monitoring information.
This is the information I see on the blog:
>Micro Web is a web dashboard and reverse proxy for micro web applications. We believe that web apps should be built as microservices and therefore treated as a first class citizen in a microservice world. It behaves much the like the API reverse proxy but also includes support for web sockets.

This is the information I see on the blog

**Comment by asim** [comment]
What monitoring information do you want to see?

**Comment by asim** [comment]
Closing, no info provided.
