### ISSUE TITLE
Unable to use noop registry in examples/grpc/greeter/

### ISSUE THREAD

**Issue by mohanraj-r** [micro/examples#27]
I am trying to use the [examples/grpc/greeter](https://github.com/micro/examples/tree/master/grpc/greeter) with the [registry/noop](https://github.com/micro/go-plugins/tree/master/registry/noop) by using `go run cli/main.go --registry=noop] but I am not able to get it to work - I get an error about unsupported/unrecognized registry. 

1. Is there something else that needs to be done to get the noop registry? 
2. Is the assumption that if we don't want to use a registry, but want to hardcode/hand-wire service orchestration (for the first iteration of the handful of services we are developing atleast) - we can use the noop registry?

**Comment by asim** [comment]
Only consul and mdns plugins are imported by default. You need to import the plugin. See go-plugins readme for info.
