### ISSUE TITLE
gin error

### ISSUE THREAD

**Issue by aofengli** [micro/examples#29]
I run the gin example：

`go run greeter/srv/main.go`
`go run greeter/api/gin/gin.go`
`micro api --handler=http`

I use postman to request `http://localhost:8080/greeter`

The result I got was:
`502 - No server or forwarder data received (Privoxy@localhost)`
but I use postman to request `http://localhost:58459/greeter` 
the 58459 is gin run port
The result I got was:
`{
    "message": "Hi, this is the Greeter API"
}
`
why?
I hope that you can give me the answer. thx！
@asim

**Comment by asim** [comment]
I think this is a Privoxy issue, not a micro issue.

**Comment by aofengli** [comment]
@asim  
oh, I think it may be that my mac os has opened the privoxy process.
you are right！ thx
