### ISSUE TITLE
RabbitMQ: Example where you have a long-lived queue?

### ISSUE THREAD

**Issue by johnwyles** [micro/examples#35]
I have simplified your example and also added `amqp.Persistent` (although even this feels hackish). This code will result in no Queue being set in RabbitMQ and thus all messages it logs lost as it functions more as a push and forget rather than enqueuing:

```
package main

import (
	"fmt"
	"log"
	"time"

	"github.com/micro/go-micro/broker"
	"github.com/micro/go-micro/cmd"
	"github.com/streadway/amqp"
	"github.com/micro/go-plugins/broker/rabbitmq"
)

func main() {
	cmd.Init()
	broker.Init()
	broker.Connect()
        tick := time.NewTicker(time.Second)
	i := 0
	for _ = range tick.C {
		msg := &broker.Message{
			Header: map[string]string{"id": "1"},
			Body: []byte("hello"),
		}
		if err := broker.Publish("go.micro.topic.foo", msg, rabbitmq.DeliveryMode(amqp.Persistent)); err != nil {
			log.Printf("[pub] failed: %v", err)
		} else {
			fmt.Println("[pub] pubbed message:", string(msg.Body))
		}
		i++
	}
}
```

This is the [example from RabbitMQ](https://github.com/rabbitmq/rabbitmq-tutorials/blob/master/go/new_task.go):

```
package main

import (
	"log"

	"github.com/streadway/amqp"
)

func main() {
	conn, _ := amqp.Dial("amqp://guest:guest@localhost:5672/")
	defer conn.Close()

	ch, _ := conn.Channel()
	defer ch.Close()

	q, _ := ch.QueueDeclare(
		"task_queue", // name
		true,         // durable
		false,        // delete when unused
		false,        // exclusive
		false,        // no-wait
		nil,          // arguments
	)

	body := "hello"
	ch.Publish(
		"",     // exchange
		q.Name, // routing key
		false,  // mandatory
		false,
		amqp.Publishing{
			DeliveryMode: amqp.Persistent,
			ContentType:  "text/plain",
			Body:         []byte(body),
		})
	log.Printf(" [x] Sent %s", body)
}
```

If you will notice the RabbitMQ example sets the `QueueDeclare` on the Channel to `task_queue`. This is **key** because it is what allows the queued items to persist.  They also do other things like make the Queue durable (in case RabbitMQ dies).  How is something like the latter example accomplished with micro?

**Comment by johnwyles** [comment]
@gstarikov @mgrachev

**Comment by asim** [comment]
See https://godoc.org/github.com/micro/go-plugins/broker/rabbitmq for setting options. My goal has always been to create a simplified abstraction over any message broker to provide fire and forget semantics. Others seem to want extra features of rabbitmq. I always recommend people use rabbitmq directly. Our goal is not to support all the features of rabbitmq or even provide a feature rich client. It's to provide a simplified messaging abstraction.
