### ISSUE TITLE
Subscriber handle method return error is invalid？

### ISSUE THREAD

**Issue by mlboy** [micro/examples#38]
Subscriber handle method return error is invalid？

eg:

type Consumer struct{}

func (s *Consumer) Process(ctx context.Context, event *proto.Event) error {
	log.Logf("recvied data: %+v\r\n", event)
	return fmt.Errorf("xxx")
}

return a error ,how i get this error?

**Comment by asim** [comment]
The error is an indicator to the underlying messaging system whether to requeue, not ack or whatever else. Its implementation dependent. You don't get any error. How would you expect the error to be handled? Who would this go to?

**Comment by mlboy** [comment]
it is means that if the return error is returned, it will be requeue? like ACK?

**Comment by asim** [comment]
Depending on the implementation yes.
