### ISSUE TITLE
How to run sidecar_server.py?

### ISSUE THREAD

**Issue by darren** [micro/examples#50]
I try to run the python `sidecar_server.py` while still using `greeter/api/api.go` as the api, here's the steps

```bash
# start the api
micro api --handler=api

# start the proxy so that sidecar_server can register itself
micro proxy

# start the api microservice
go run greeter/api/api.go

# start the python sidecar
python greeter/srv/python/sidecar_server.py 
```

Now try to access the api:

```bash
curl  "http://localhost:8080/greeter/say/hello?name=abc"
```
it returns 
```
{"id":"go.micro.client.codec","code":500,"detail":"proto: protorpc.Response: illegal tag 0 (wire type 0)","status":"Internal Server Error"}
```

The problem is that sidecar_server.py talks json-rpc, while greeter/api/api.go trying talk to it using grpc?

There is an example using jsonrpc as in https://github.com/micro/examples/issues/9#issuecomment-321618701

but NewJsonRequest is no longer available

```go
import (
        "github.com/micro/go-micro/client"
)

// define the request
req := client.NewJsonRequest("go.micro.srv.greeter", "Say.Hello", &hello.Request{Name: "John"})
```

So how make this sidecar_server.py working?

**Comment by asim** [comment]
This is currently a WIP. We'll update soon.
