### ISSUE TITLE
Disabled examples list

### ISSUE THREAD

**Issue by printfcoder** [micro/examples#59]
Hi, guys, please comment the examples which are disabled when you are running them. 

Just add a comment with a link to the disabled example.

Thanks

**Comment by jinxingf** [comment]
I just running the ['greeter'](https://github.com/micro/examples/tree/master/greeter) example and found that the greeter client will raise error for "Name cannot be blank" when you call the rest api "curl  -H 'Content-Type: application/json'  "http://localhost:8080/greeter/say/hello?name=John"" to test the service.
