### ISSUE TITLE
a question about micro api

### ISSUE THREAD

**Issue by panjf2000** [micro/examples#6]
i read the examples of micro api and found out a question,
this is the desc from micro-api:
Make an RPC call via /rpc with content-type set to json
```
$ curl -H 'Content-Type: application/json' \
	-d '{"service": "go.micro.srv.greeter", "method": "Say.Hello", "request": {"name": "Asim Aslam"}}' \
	http://localhost:8080/rpc
```
i downloaded the examples/greeter codes , and according to the desc from micro-api, i should run "go run examples/greeter/srv/main.go &&go run examples/greeter/api/api.go&&micro api", then i can get the above cmd work.

but i found out that i can just run "go run examples/greeter/srv/main.go&&micro api" and the above curl cmd can work! so that means i does not need the codes of examples/greeter/api, only needs the codes of examples/greeter/srv，and why is that？what is the meaning of the codes of examples/greeter/api

**Comment by asim** [comment]
Please direct questions to the slack in future. We use issues only for bugs and related things.

Please look at this blog post to get a better understanding of the different types of services https://micro.mu/blog/2016/04/18/micro-architecture.html. Micro uses tooling to logically separate the different concerns of software architecture. The API gateway serves API services focused on public facing consumption whereas backend services are for internal use. The API gateway has a /rpc endpoint to allow you to short circuit this and go directly to a backend service. If you read the docs you'll see the firs thing it says 'curl "http://localhost:8080/greeter/say/hello?name=Asim+Aslam'. Note the path "/greeter/say/hello" meaning service greeter and method Say.Hello. This allows construction of an API as microservices.
