### ISSUE TITLE
greeter/api/graphql example cannot be compiled

### ISSUE THREAD

**Issue by bytefly** [micro/examples#61]
The compile error output is :
`graphql/generated.go:236:3: unknown field 'IsMethod' in struct literal of type graphql.ResolverContext
graphql/generated.go:263:3: unknown field 'IsMethod' in struct literal of type graphql.ResolverContext
graphql/generated.go:294:3: unknown field 'IsMethod' in struct literal of type graphql.ResolverContext
graphql/generated.go:325:3: unknown field 'IsMethod' in struct literal of type graphql.ResolverContext
graphql/generated.go:349:3: unknown field 'IsMethod' in struct literal of type graphql.ResolverContext
graphql/generated.go:376:3: unknown field 'IsMethod' in struct literal of type graphql.ResolverContext
graphql/generated.go:400:3: unknown field 'IsMethod' in struct literal of type graphql.ResolverContext
graphql/generated.go:427:3: unknown field 'IsMethod' in struct literal of type graphql.ResolverContext
graphql/generated.go:454:3: unknown field 'IsMethod' in struct literal of type graphql.ResolverContext
graphql/generated.go:481:3: unknown field 'IsMethod' in struct literal of type graphql.ResolverContext
graphql/generated.go:481:3: too many errors
`

The reason is gqlgen version in go.mod is v0.7.1, which doesn't contain member IsMethod in struct ResolverContext. The fix method is changing the version to v0.8.3.

**Comment by asim** [comment]
Updated. I believe this should be fixed.
