### ISSUE TITLE
Event Example Issue after Server.Wait Commit

### ISSUE THREAD

**Issue by subzerobo** [micro/examples#63]
Hi, it seems the Event Example does not work anymore after waitgroup update in the last commit of go-micro it throws an error after api call, try it please 

https://github.com/micro/examples/tree/master/event

http: panic serving 192.168.14.39:56220: runtime error: invalid memory address or nil pointer dereference
goroutine 29 [running]:
net/http.(*conn).serve.func1(0xc0001ce1e0)
        /usr/local/Cellar/go/1.11.4/libexec/src/net/http/server.go:1746 +0xd0
panic(0x17726e0, 0x1e49ec0)
        /usr/local/Cellar/go/1.11.4/libexec/src/runtime/panic.go:513 +0x1b9
sync.(*WaitGroup).state(...)
        /usr/local/Cellar/go/1.11.4/libexec/src/sync/waitgroup.go:33
sync.(*WaitGroup).Add(0x0, 0x1)
        /usr/local/Cellar/go/1.11.4/libexec/src/sync/waitgroup.go:54 +0x26
github.com/micro/go-micro/server.(*rpcServer).createSubHandler.func1(0x191d860, 0xc00000c440, 0x0, 0x0)
        /Users/alikaviani/Projects/go-workspace/src/github.com/micro/go-micro/server/subscriber.go:247 +0x360
github.com/micro/go-micro/broker.(*httpBroker).ServeHTTP(0xc00016e000, 0x191e460, 0xc0002081c0, 0xc000188300)
        /Users/alikaviani/Projects/go-workspace/src/github.com/micro/go-micro/broker/http_broker.go:334 +0x69b
net/http.(*ServeMux).ServeHTTP(0xc00016c0c0, 0x191e460, 0xc0002081c0, 0xc000188300)
        /usr/local/Cellar/go/1.11.4/libexec/src/net/http/server.go:2361 +0x127
net/http.serverHandler.ServeHTTP(0xc000179ad0, 0x191e460, 0xc0002081c0, 0xc000188300)
        /usr/local/Cellar/go/1.11.4/libexec/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc0001ce1e0, 0x191f020, 0xc0000781c0)
        /usr/local/Cellar/go/1.11.4/libexec/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
        /usr/local/Cellar/go/1.11.4/libexec/src/net/http/server.go:2851 +0x2f5
2019/05/28 18:39:16 http: panic serving 192.168.14.39:56221: runtime error: invalid memory address or nil pointer dereference
goroutine 9 [running]:
net/http.(*conn).serve.func1(0xc0000c41e0)
        /usr/local/Cellar/go/1.11.4/libexec/src/net/http/server.go:1746 +0xd0
panic(0x17726e0, 0x1e49ec0)
        /usr/local/Cellar/go/1.11.4/libexec/src/runtime/panic.go:513 +0x1b9

**Comment by asim** [comment]
Thanks, fixed with an update to go-micro. Please do go get -u

**Comment by subzerobo** [comment]
Hi Asim, the error is gone but the example does not work as mentioned in the readme file, or maybe i'm not running the right way as you mentioned when we run the micro API like this 
`micro API --handler=event --namespace=go.micro.evt` all request made to the API gateway like this `curl -d '{"name": "John"}' http://localhost:8080/user/login` would be published in **message broker** in topic "go.micro.evt.user" with event name login but it does not work and the log on line 16 of [https://github.com/micro/examples/blob/master/event/srv/main.go](https://github.com/micro/examples/blob/master/event/srv/main.go) won't show up !

I've even enabled the nats broker and nats transport in the micro and build the micro with those plugins and ran the micro API like this 

`micro --transport=nats --broker=nats api --handler=event --namespace=go.micro.evt` but did not got the message in nats when i've listened on go.micro.evt.* or event go.* itself !

could you please elaborate a little bit about the event handler in micro api maybe i am wrong !
