### ISSUE TITLE
Event Example Issue 

### ISSUE THREAD

**Issue by subzerobo** [micro/examples#64]
Hi Asim,
Following the issue [https://github.com/micro/examples/issues/63](https://github.com/micro/examples/issues/63) as you mentioned the error is gone but the example does not work as mentioned in the readme file, or maybe i'm not running the right way as you mentioned when we run the micro API like this 
`micro API --handler=event --namespace=go.micro.evt` all request made to the API gateway like this `curl -d '{"name": "John"}' http://localhost:8080/user/login` would be published in **message broker** in topic "go.micro.evt.user" with event name login but it does not work and the log on line 16 of [https://github.com/micro/examples/blob/master/event/srv/main.go](https://github.com/micro/examples/blob/master/event/srv/main.go) won't show up !

I've even enabled the nats broker and nats transport in the micro and build the micro with those plugins and ran the micro API like this 

`micro --transport=nats --broker=nats api --handler=event --namespace=go.micro.evt` but did not got the message in nats when i've listened on go.micro.evt.* or event go.* itself !

could you please elaborate a little bit about the event handler in micro api maybe i am wrong !

**Comment by asim** [comment]
I'm testing this exact thing locally and it works. So its unclear why its failing. I receive the message and the event is logged. Are your dependencies up to date?

**Comment by subzerobo** [comment]
I think yes, am i right with the broker switch ?  does --broker=nats means that the event data will be published through nats?

**Comment by asim** [comment]
Are you doing the same with the service?

**Comment by subzerobo** [comment]
It resolved I did a complete cleanup on $GOPATH it did the trick! thank you
