### ISSUE TITLE
service error {"id":"go.micro.client","code":408,"detail":"call timeout: context deadline exceeded","status":"Request Timeout"}

### ISSUE THREAD

**Issue by CodingYuanLiu** [micro/examples#70]
Hello, I had a problem in ./service example.</br> (I'm using the win10 OS.)</br> First of all I ran consul by `consul agent -dev`, And then I ran the greeter server by </br>`go run main.go --registry=consul`.
``` bash
2019/07/05 16:26:35 Transport [http] Listening on [::]:62272
2019/07/05 16:26:35 Broker [http] Connected to [::]:62273
2019/07/05 16:26:35 Registry [consul] Registering node: greeter-cd055fee-9664-4244-b433-8b5b353f64da
```
 Later I was able to see these two services at `localhost:8500` and `micro --registry=consul list services`.</br> However, when I tried to run the client by `go run main.go --run_client --registry=consul`, I received a timeout error as the title says:</br>
`{"id":"go.micro.client","code":408,"detail":"call timeout: context deadline exceeded","status":"Request Timeout"}`
</br>What's more, I also received a 408 error by `micro --registry=consul health greeter`
</br> So what's wrong with the simple helloworld demo?

**Comment by CodingYuanLiu** [comment]
By the way, when I access `http://localhost:8500/v1/catalog/service/greeter`, I can see the information of the service the "ServerAddress" is `172.25.6.17`. However, I can't find the ip address `172.25.6.17`  in the list shown by  the command `ipconfig`  (or `arp -a`).

**Comment by CodingYuanLiu** [comment]
Oh I find out that the problem is on the `ServerAddress`. I fix it by:
``` go
service := micro.NewService(
		micro.Name("greeter"),
		micro.Address("127.0.0.1:54782"), // The port can be choosed randomly
	)
```

**Comment by yoki123** [comment]
After I specified the ip:port, I also got an error.

`curl "http://localhost:8080/greeter/say/hello?name=John"`
got 
`{"id":"go.micro.api","code":500,"detail":"error during request: unknown field \"name\" in go_api.Request","status":"Internal Server Error"}`


`curl "http://localhost:8080/greeter/say/hello"`
got
`{"id":"go.micro.api.greeter","code":400,"detail":"Name cannot be blank","status":"Bad Request"}`


after added [ --handler=api](https://github.com/micro/examples/issues/71#issuecomment-557750988) for `micro api`

it works!
