### ISSUE TITLE
Unknown Field Name in go_api.Request

### ISSUE THREAD

**Issue by FarhanSajid1** [micro/examples#71]
I am having an issue with one of the examples, the greeter sample in particular. When I pass in the ?name=john into the browser, I get this response.

{"id":"go.micro.api","code":500,"detail":"error during request: unknown field \"name\" in go_api.Request","status":"Internal Server Error"}

Is there any way to solve this?

**Comment by k1ng440** [comment]
which example are you using?

**Comment by FarhanSajid1** [comment]
I am doing the greeter example, the one from the api gateway. I followed ran the example, and that error continues to occur.
https://micro.mu/docs/go-micro.html

**Comment by YHWL** [comment]
I have a problem and look forward to guidance，Thanks.
when I run script:

`go run api/api.go `
`micro api --handler=api`
`curl http://localhost:8080/greeter/say/hello?name=John`

Print rrror message:
`{"id":"go.micro.client","code":500,"detail":"error selecting go.micro.srv.greeter node: not found","status":"Internal Server Error"}`

example:[greeter](https://github.com/micro/examples/tree/master/greeter)
environment： Mac  
go version: go version go1.12.7 darwin/amd64

**Comment by FarhanSajid1** [comment]
Are you running consul? That might be the primary cause.

**Comment by YHWL** [comment]
> Are you running consul? That might be the primary cause.

Yes, I run consul first, but get the same error message
`consul agent -dev`

**Comment by YHWL** [comment]
> Are you running consul? That might be the primary cause.

I found out why.Thank you! 
I didn't run the script
`go run srv/main.go`
So, The server register failed.

**Comment by fanziyong** [comment]
i got it. this --handler=api not setting
