### ISSUE TITLE
cannot find package github.com/micro/go-plugins/selector/static

### ISSUE THREAD

**Issue by Alllfred** [micro/examples#72]
I try run k8s [examples](https://github.com/micro/examples/tree/master/kubernetes#installing-micro) and when I try `go get github.com/micro/kubernetes/cmd/micro` I got a error for `cannot find package "github.com/micro/go-plugins/selector/static`

Then I try `go get github.com/micro/go-plugins`, but it doesn't work. So how do I fix it ?

**Comment by FarhanSajid1** [comment]
Same issue

**Comment by kavyash** [comment]
I have the same issue. Did anyone find a way around?

**Comment by k1ng440** [comment]
it has moved to the `client` directory

`github.com/micro/go-plugins/client/selector/static`

https://github.com/micro/go-plugins/tree/master/client/selector/static

**Comment by FarhanSajid1** [comment]
So how would we run go get on this?

**Comment by asim** [comment]
github.com/micro/kubernetes has been deprecated. We maintain an example repo here to guide usage. All examples have been updated to reflect the move of the selector. Please update your code and make use of go mod.

**Comment by asim** [comment]
I've updated the readme to reflect those changes also

**Comment by FarhanSajid1** [comment]
Thank you, I got it working
