### ISSUE TITLE
go mod tidy 410

### ISSUE THREAD

**Issue by songxuexian** [micro/examples#73]
go mod download

> go: finding github.com/micro/go-micro/config v0.13.3
> go: finding github.com/micro/go-micro/service/grpc v0.9.0
> go: finding github.com/micro/go-micro/agent v0.1.0
> go: finding github.com/micro/go-micro/util/log v0.1.0
> go: github.com/micro/go-micro/service/grpc@v0.9.0: unexpected status (https://goproxy.io/github.com/micro/go-micro/service/grpc/@v/v0.9.0.info): 410 Gone
> go: github.com/micro/go-micro/agent@v0.1.0: unexpected status (https://goproxy.io/github.com/micro/go-micro/agent/@v/v0.1.0.info): 410 Gone
> go: github.com/micro/go-micro/util/log@v0.1.0: unexpected status (https://goproxy.io/github.com/micro/go-micro/util/log/@v/v0.1.0.info): 410 Gone
> go: github.com/micro/go-micro/config@v0.13.3: unexpected status (https://goproxy.io/github.com/micro/go-micro/config/@v/v0.13.3.info): 410 Gone
> go: error loading module requirements

go build (direct)

> go: finding github.com/micro/go-micro/config v0.13.3
> go: finding github.com/micro/go-micro/util/log v0.1.0
> go: finding github.com/micro/go-micro/service/grpc v0.9.0
> go: finding github.com/micro/go-micro/agent v0.1.0
> go: github.com/micro/go-micro/config@v0.13.3: unknown revision config/v0.13.3
> go: github.com/micro/go-micro/util/log@v0.1.0: unknown revision util/log/v0.1.0
> go: github.com/micro/go-micro/service/grpc@v0.9.0: unknown revision service/grpc/v0.9.0
> go: github.com/micro/go-micro/agent@v0.1.0: unknown revision agent/v0.1.0
> go: error loading module requirements

**Comment by zhaoshenglong** [comment]
@songxuexian 
Did you export `GOPROXY` environment variable? Some of the dependencies of `go-micro` are in `golang/x/` and these awesome lib have been blocked by the internet policy. 

If you want to download `go-micro`, you have three choices:
1. set `GOPROXY` environment variable
 > export GOPROXY=https://goproxy.io

Or you can set `GOPROXY` in ~/.bashrc if you are using linux. </br>

In this way, I think you can download dependencies, but I am not very sure.

If you didn't succeed, you can clean the go module cache
> go clean --modcache

After that, 
> go mod tidy

However, proxy may not work very well, and there still exists some libs that can not be accessed. 

2.  download from github and extract

This way need many manual work, and is not suggested

3. set terminal proxy

There are many ways to set terminal proxy. I am using privoxy. You may consult your search engine to get details.

May it helps you ~

**Comment by songxuexian** [comment]
@zhaoshenglong 
thanks for you replay.
First, I was set ```GOPROXY``` environment variable . ``` export GOPROXY=https://goproxy.io```
Then, I try the '1' that you have been said. but, it also not work.

Now, I update the code, so it is working.
