### ISSUE TITLE
go mod file error nats.go v1.8.2-0.20190711203405-98cd22864ded

### ISSUE THREAD

**Issue by calentang** [micro/examples#74]
replace github.com/nats-io/nats.go => github.com/nats-io/nats.go v1.8.2-0.20190711203405-98cd22864ded

hello, i saw the code of github.com/nats-io/nats.go  the newest version is v1.8.1 ,but i found  the github.com/nats-io/nats.go version is v1.82 that in your go.mod file.

it cause me can get the github.com/nats-io/nats.go code. is that correct?

**Comment by ralfbawg** [comment]
me too,please fix

**Comment by milosgajdos83** [comment]
This is `go mod` acting really stupid as you can see [here](https://github.com/golang/go/issues/33076) and [here](https://github.com/nats-io/nats.go/issues/493#issuecomment-511020264).

We will try to fix this issue, but feel free to open a PR.
