### ISSUE TITLE
RPC call got an EOF error after graceful shutdown the service

### ISSUE THREAD

**Issue by ginuerzh** [micro/examples#8]
I invoke an time consuming RPC call (roundtrip is about 20s), then issue a shutdown command (^C) to the service before the RPC call returns. The service waits for the return of the call, that is OK. It does not return the result of the RPC call, but an error below when the call ends:
```json
{"id":"go.micro.client.transport","code":500,"detail":"unexpected EOF","status":"Internal Server Error"}
```

**Comment by asim** [comment]
I'll update the example later but this was just a way of demonstrating how to wait on handlers for a graceful shutdown. It did not guarantee response to client. Graceful has been built into the server now.

Currently you can invoke like this https://github.com/micro/go-micro/blob/master/function.go#L55L57

```
service.Server().Init(
    server.Wait(true),
)
```

**Comment by asim** [comment]
Examples updated. Closing issue.

**Comment by imneov** [comment]
When we use this code( https://github.com/micro/go-micro/blob/master/function.go#L55L57) tells the server to wait for requests to finish before exiting, but when all sync.WaitGroup is done.
1)  server and client conn't finish close socket 
2)  client con't refresh server nodes
so, some error below when the server ends:
```
2018/10/10 18:20:04 error, {"id":"go.micro.client.transport","code":500,"detail":"EOF","status":"Internal Server Error"}
2018/10/10 18:20:04 error, {"id":"go.micro.client.transport","code":500,"detail":"EOF","status":"Internal Server Error"}
2018/10/10 18:20:04 error, {"id":"go.micro.client","code":500,"detail":"connection error: dial tcp 192.168.99.1:53306: connect: connection refused","status":"Internal Server Error"}
2018/10/10 18:20:04 error, {"id":"go.micro.client","code":500,"detail":"connection error: dial tcp 192.168.99.1:53306: connect: connection refused","status":"Internal Server Error"}
```

So I add some code:
https://github.com/imneov/go-micro/compare/master...imneov:patch-1
