### ISSUE TITLE
how to use proxy at version 1.9.1

### ISSUE THREAD

**Issue by laoqiu** [micro/examples#80]
I find then proxy add new option, protocol and endpoint

In example, 
```
> micro proxy --endpoint=http://127.0.0.1:4000
> python rpc_server.py
> python rpc_client.py
# {'error': {'code': -32600, 'message': 'Invalid Request'}, 'id': None, 'jsonrpc': '2.0'}
```

How to use the new proxy?

**Comment by laoqiu** [comment]
I tried other option and all returned different errors.

````
> micro proxy --protocol=http
# {'id': '', 'result': None, 'error': '{"id":"","code":500,"detail":"Post localhost:9090: unsupported protocol scheme \\"localhost\\"","status":"Internal Server Error"}'}

> micro proxy
# {'id': '', 'result': None, 'error': '{"id":"go.micro.client","code":500,"detail":"service : not found","status":"Internal Server Error"}'}
````

**Comment by asim** [comment]
Were you using the proxy before? Was it working? What's the expected case? I have a feeling the example is out of date.

**Comment by laoqiu** [comment]
I used it after sidecar became proxy,
At that time, It working, data could be returned from python server, just like other micro-services.
I want to know how to use proxy in this version, 
no way found in source code.

**Comment by laoqiu** [comment]
I think the parameters for requesting python server need to be change like this:
```
b'{"method": "example.call", "params": ["{\\"name\\": \\"test\\"}"], "jsonrpc": "2.0", "id": 0}'
```
This is the case now:
```
b'{\n    "name": "test"\n}'
```
