### ISSUE TITLE
Indicating Other Broker While Start Gateway.

### ISSUE THREAD

**Issue by bimoyong** [micro/examples#89]
Hello everyone, 

I wonder is it possible if I start the API Gateway type Event Handler with Kafka?
The thing inside bracket pair **[]** in below code is what I did try but not success. Probably the cause of not importing the Kafka plugin but no idea how to do it.
`micro [--broker=kafka] api --handler=event --namespace=go.micro.evt`

The help is really appreciated.
Thanks.

**Comment by asim** [comment]
The Kafka broker is not included by default. Please see the readme in the go-plugins directory for how they should be included.

**Comment by bimoyong** [comment]
Thank so much.
Per your guide I can indicated success Kafka as broker for my micro service.
But what exact I mean is how I can do it for the gateway which starts by command below:
`micro api --handler=event --namespace=go.micro.evt`
