### ISSUE TITLE
JsonRpc Examples

### ISSUE THREAD

**Issue by JasonGLYao** [micro/examples#9]
could you please help to provide some JsonRPC examples ?
thanks.

**Comment by asim** [comment]
What kind of json rpc examples? Between services? Via the api? In the sidecar? Completely plain?

If a service encounters the content-type application/json then it will assume json-rpc. You can send json to a service like so.

```
type FooRequest struct {
    Message string
}

type FooResponse struct {
   Reply string
}

req := client.NewRequest("my.service", "My.Method", &FooRequest{Message: "Hello"})
rsp := new(FooResponse)
err := client.Call(context.TODO(), req, rsp)
```

**Comment by JasonGLYao** [comment]
Hi,
Here is the sample code that does not work well  because client side could not receive data from server side,could you please help me to adjust somewhere to make it work as expected?  

Thanks.


//--------------------------server side
package main

import (
	"encoding/json"
	"fmt"
	"log"

	"github.com/micro/go-micro"
	api "github.com/micro/micro/api/proto"
	"golang.org/x/net/context"
)

type FooRequest struct {
	Message string
}

type Enterprise struct {
}

func (r *Enterprise) GetAll(ctx context.Context, req *api.Request, rsp *api.Response) error {
	rsp.StatusCode = int32(200)
	var b = &FooRequest{Message: "Hell--o"}
	bs, _ := json.Marshal(b)
	rsp.Body = string(bs)
	fmt.Println(rsp.Body)
	return nil
}

func main() {
	service := micro.NewService(
		micro.Name("Jason.Demo"),
		micro.Version("latest"),
	)

	service.Init()
	service.Server().Handle(
		service.Server().NewHandler(new(Enterprise)),
	)
	if err := service.Run(); err != nil {
		log.Fatal(err)
	}

}
//--------------------------Client Side
package main

import (
	"fmt"

	"github.com/micro/go-micro"
	"golang.org/x/net/context"
)

type FooRequest struct {
	Message string
}

func main() {

	service := micro.NewService(
		micro.Name("Jason.Demo"),
		micro.Version("latest"),
		micro.Metadata(map[string]string{
			"type": "helloworld",
		}),
	)
	var rs = new(FooRequest)

	var c = service.Client()
	var req = c.NewJsonRequest("Jason.Demo", "Enterprise.GetAll", map[string]interface{}{"hello": "world"})
	err := c.Call(context.TODO(), req, rs)
	if err != nil {
		fmt.Println(err)
		fmt.Println("world")
	} else {
		fmt.Println(rs) ///output &{}<---can not get what I wanted
	}
}
//

**Comment by asim** [comment]
You are conflating a number of different things. You have api.Request and api.Response in your handler but then you're calling this via a client but setting a nil request and a FooRequest as the response?! This makes literally no sense. Also I don't understand why you are trying to send "jsonrpc" and from where.

api.Request and api.Response are used by api services when they are to be called via the micro api gateway. Here's documentation on the api gateway https://micro.mu/docs/api.html. Here's an example of an api service https://github.com/micro/examples/blob/master/greeter/api/api.go. A http request would be made to the api gateway which could contain json, this would then be passed on to the api service.

Let's ignore that for now and stick with just a client and service. Let's say you have the greeter service which you can find here https://github.com/micro/examples/blob/master/greeter/srv/main.go. Sending a request to this is quite simple. Here's the client code.

```
package main

import (
        "fmt"

        "github.com/micro/go-micro/client"
        "github.com/micro/go-micro/cmd"
        hello "github.com/micro/examples/greeter/srv/proto/hello"

        "golang.org/x/net/context"
)

func main() {
        cmd.Init()

        // Use the generated client stub
        cl := hello.NewSayClient("go.micro.srv.greeter", client.DefaultClient)

        // Make request
        rsp, err := cl.Hello(context.TODO(), &hello.Request{
                Name: "John",
        })
        if err != nil {
                fmt.Println(err)
                return
        }

        fmt.Println(rsp.Msg)
}
```

This will use protobuf but if you want to explicitly send json you can do the following

```
package main

import (
        "fmt"

        "github.com/micro/go-micro/client"
        "github.com/micro/go-micro/cmd"
        hello "github.com/micro/examples/greeter/srv/proto/hello"

        "golang.org/x/net/context"
)

func main() {
        cmd.Init()

        // define the request
        req := client.NewJsonRequest("go.micro.srv.greeter", "Say.Hello", &hello.Request{Name: "John"})

        // define the response
        rsp := new(hello.Response)

        // make the request
        err := client.Call(context.TODO(), req, rsp)
        if err != nil {
                fmt.Println(err)
                return
        }

        fmt.Println(rsp.Msg)
}
```

This explicitly defines a json request. Note it's still using the Request and Response types expected by the greeter service handler.

Please join the slack for further discussion if needed.
