### ISSUE TITLE
How to test k8s locally

### ISSUE THREAD

**Issue by bigrocs** [micro/examples#90]
How to test k8s locally
![image](https://user-images.githubusercontent.com/15796287/66251389-2f7d0d00-e782-11e9-9f55-77779e939bc4.png)
2019/10/05 15:10:53 stat /var/run/secrets/kubernetes.io/serviceaccount: no such file or directory
exit status 1

**Comment by asim** [comment]
Run in minikube or another kubernetes based development environment?

https://github.com/kubernetes/minikube

**Comment by bigrocs** [comment]
I may have asked wrong.
How do I configure two versions of latest and kubernetes via dockerfile
Two main.go and Two dockerfile?

**Comment by bigrocs** [comment]
There are no parameter settings via a main.go
Two dockerfile generation

**Comment by asim** [comment]
working on it
