### ISSUE TITLE
client can't find the service but server register successfully

### ISSUE THREAD

**Issue by CodingSinger** [micro/examples#98]
` go run main.go --registry=mdns`
I start the greeter server of the example project successfully  and the console print the log
```
2019-11-11 09:30:00.912112 I | Server [grpc] Listening on [::]:53358
2019-11-11 09:30:00.912338 I | Broker [http] Connected to [::]:53359
2019-11-11 09:30:00.913182 I | Registering node: go.micro.srv.greeter-2dc6ce3d-d7b3-4e36-a2a2-1373546b12a9

```
`go run main.go --registry=mdns`
then i boot the  client but client can't run normal  and log 
`{"id":"go.micro.client","code":500,"detail":"service go.micro.srv.greeter: not found","status":"Internal Server Error"}`
 
How can I solve this problem?

**Comment by ngray1747** [comment]
+1

**Comment by ngray1747** [comment]
If you are using MacOS, check your firewall. 
See here : [](https://github.com/micro/go-micro/issues/435)

**Comment by binuedwin** [comment]
hi,

i am facing the same issue in my linux machine, but the firewall is disabled. Even than {"id":"go.micro.client","code":500,"detail":"service go.micro.srv.greeter: not found","status":"Internal Server Error"}

**Comment by viiftw** [comment]
The files in the proto directory are not compatible with the latest version of go-micro
If you use the latest version of **go-micro** and the **micro**-runtime try rebuilding the proto file with the latest version of **protobuf**, **proto-gen-go**, **proto-gen-micro**:
[github.com/golang/protobuf](url)
[github.com/golang/protobuf/proto](url)
[github.com/golang/protobuf/proto,protoc-gen-go](url)
[github.com/micro/protoc-gen-micro](url)

**Comment by egyel** [comment]
I've had the same issue.
In my case, I got it because I had an older version of micro. Running the 'go get -u ...' did not updated it properly. I had to delete the $GOPATH/src/github.com/micro folder first and than run 'go get -u ...', which fixed the problem.

**Comment by k1ng440** [comment]
Please use go module

**Comment by vtolstov** [comment]
if you don't on mac os, have disabled firewall and go-micro/v2 - create new issue plese.
